### PR TITLE
allign semicolon to bottom

### PR DESCRIPTION
**Pull request by CodeGuy92**
as the scratch easter egg lives

### CODE REVIEW

**Comment by CodeGuy92** [comment]
Actually set left float to 15 instead of 0

**Comment by CodeGuy92** [comment]
@The64thCucumber

**Comment by Time-dragon** [comment]
@The64thCucumber check please

**Comment by The64thCucumber** [comment]
Oops I forgot about Github and didn't check it

**Comment by CodeGuy92** [comment]
lmao

**Pull request merged**
